check if window and navigator exist
tomisu/react-element-scroll-hook pull request #2
Opened 2020-05-15 13:28 UTC by skrln

In cases where this package is imported in a Server Sided Rendering context, there is no window object and also no navigator. I'd like to propose checks for window because builds would fail on `"navigator" is not available during server side rendering.`

With these checks the code is only executed when actually inside a browser.

2020-06-19 13:00 UTC, skrln commented
Hey @tomisu . Just a little bump on this pull request. Let me know if you have questions about it.
Thanks in advance.

2020-06-23 07:58 UTC, tomisu requested changes
Yeah, this looks right.

Can you bump the version in `package.json` to `1.1.0`?

I'll merge and publish it after that :+1: 

Thanks a lot for the contribution!

2020-06-23 12:05 UTC, skrln commented
Let me know if I can do anything else.

Cheers!

2020-06-23 14:14 UTC, tomisu approved these changes

2020-06-23 14:14 UTC, merged